//Cleric Subclasses

divineDomains = [
  {
    "divineDomain":"",
    "divineDomainFeature1":"",
    "divineDomainFeature2":"",
    "divineDomainFeature3":"",
    "divineDomainFeature4":"",
  },
];

//Cleric Class Boons

var classBoon = [
  {
    "name":"Deepened Divinity",
    "cost":3,
    "prereq":"Cleric or Paladin level 3rd",
    "desc":"You gain one additional use of Channel Divinity per long rest.",
    "type":"Class Boon",
  },
  {
    "name":"Improved Divine Intervention",
    "cost":3,
    "prereq":"Cleric level 10th",
    "desc":"When you use Divine Intervention, you gain a 10% greater chance of intervention.",
    "type":"Class Boon",
  },
  {
    "name":"Encompassing Abjure",
    "cost":2,
    "prereq":"Arcana Cleric level 3rd",
    "desc":"You can target up to two additional celestials, elementals, fey, or fiends when you use Arcane Abjuration.",
    "type":"Class Boon",
  },
  {
    "name":"Weave Sapper",
    "cost":3,
    "prereq":"Arcana Cleric level 9th",
    "desc":"When you end a spell that you did not cast on a creature or object, you gain a number of temporary hit points equal to 1d6 * the level of the spell.",
    "type":"Class Boon",
  },
  {
    "name":"Reaping Touch",
    "cost":2,
    "prereq":"Death Cleric level 3rd",
    "desc":"When you deal damage to a creature with Touch of Death, you also gain a number of hit points equal to half the damage dealt. If this would bring your current hit points past your hit point maximum, any left over hit points become temporary hit points.",
    "type":"Class Boon",
  },
  {
    "name":"Necrotic Mastery",
    "cost":3,
    "prereq":"Death Cleric level 9th",
    "desc":"Necrotic damage dealt by your cleric spells and Channel Divinity options ignores resistance and immunity to necrotic damage. Additionally, you gain resistance to necrotic damage.",
    "type":"Class Boon",
  },
  {
    "name":"Sundering Strike",
    "cost":2,
    "prereq":"Destruction Cleric level 3rd",
    "desc":"When you score a critical hit with a weapon attack, you can choose to use Sundering Invocation. When you use it in this way, a creature has disadvantage on the saving throw.",
    "type":"Class Boon",
  },
  {
    "name":"Inured to Annihilation",
    "cost":3,
    "prereq":"Destruction Cleric level 9th",
    "desc":"You gain immunity to thunder damage.",
    "type":"Class Boon",
  },
  {
    "name":"Greater Blessing of the Forge",
    "cost":2,
    "prereq":"Forge Cleric level 3rd",
    "desc":"When you use Blessing of the Forge, the bonus to a weapon or armor becomes +2.",
    "type":"Class Boon",
  },
  {
    "name":"Hammer of Creation",
    "cost":3,
    "prereq":"Forge Cleric level 9th",
    "desc":"You can use your Channel Divinity to conduct an hour-long ritual on a magical weapon. At the end of this ritual, this weapon gains the following properties:<ul><li>This weapon ignores all resistance to Fire damage.</li><li>This weapon deals an additional 1d6 Fire damage.</li></ul>These properties last for 8 hours, or until you use your Channel Divinity again.",
    "type":"Class Boon",
  },
  {
    "name":"Grave Usher",
    "cost":2,
    "prereq":"Grave Cleric level 3rd",
    "desc":"When you reduce a creature to 0 hit points, you can choose to expend a spell slot of 1st level or higher to instantly kill them. When you kill a creature in this way, their body cannot become undead for a number of days equal to the spell slot level you expended.",
    "type":"Class Boon",
  },
  {
    "name":"Cemetary Gates",
    "cost":3,
    "prereq":"Forge Cleric level 9th",
    "desc":"When a creature within 10 meters of you dies, you can use your Channel Divinity as a reaction to bring the creature to 1 hit point instead. They also lose one level of exhaustion.",
    "type":"Class Boon",
  },
  {
    "name":"Incite Envy",
    "cost":2,
    "prereq":"Greed Cleric level 3rd",
    "desc":"When you use Incite Greed, you can choose to target a creature within range instead of a point. All creatures within the affected area that fail the saving throw must also make an additional wisdom saving throw if they get within range of the creature you choose. On a fail, they must use their action to attack that creature.",
    "type":"Class Boon",
  },
  {
    "name":"Divine Frugality",
    "cost":3,
    "prereq":"Greed Cleric level 9th",
    "desc":"The cost of material components you need for spells becomes 40% cheaper. Additionally, you do not need to provide the material components for spells that are less than 10000 wealth.",
    "type":"Class Boon",
  },
  {
    "name":"Expertise of the Ages",
    "cost":2,
    "prereq":"Knowledge Cleric level 3rd",
    "desc":"When you gain proficiency in a skill using Knowledge of the Ages, you double your proficiency bonus for that skill.",
    "type":"Class Boon",
  },
  {
    "name":"Intrusive Introspection",
    "cost":3,
    "prereq":"Knowledge Cleric level 9th",
    "desc":"You can expend a spell slot instead of your Channel Divinity to use Read Thoughts.",
    "type":"Class Boon",
  },
  {
    "name":"Cling to Life",
    "cost":2,
    "prereq":"Life Cleric level 3rd",
    "desc":"When you or a creature within 10 meters of you falls to 0 hit points, you can use your reaction to expend a spell slot. They gain a number of hit points equal to two * the level of spell slot expended. You cannot heal an undead or construct in this way.",
    "type":"Class Boon",
  },
  {
    "name":"Stolen Recovery",
    "cost":3,
    "prereq":"Life Cleric level 9th",
    "desc":"When a creature within 10 meters of you gains hit points, you can use your reaction and expend a use of your Channel Divinity to reduce all healing that creature received to 0. A creature within 10 meters of you then heals for a number of hit points equal to half of the hit points the initial target was intended to gain. You cannot heal an undead or construct in this way.",
    "type":"Class Boon",
  },
  {
    "name":"Radiant Flare",
    "cost":2,
    "prereq":"Light Cleric level 3rd",
    "desc":"When a creature is affected by your Warding Flare, they automatically miss their attack and take 1d10 + half your cleric level radiant damage.",
    "type":"Class Boon",
  },
  {
    "name":"Blinding Dawn",
    "cost":3,
    "prereq":"Light Cleric level 9th",
    "desc":"When you use Radiance of the Dawn, all creatures that fail the Constitution saving throw are also blinded for 1 minute.",
    "type":"Class Boon",
  },
  {
    "name":"Family Bond",
    "cost":2,
    "prereq":"Love Cleric level 3rd",
    "desc":"When you use Emboldening Bond, you may instead choose a number of creatures up to your Wisdom modifier. If all creatures are within 10 meters of each other, they may roll a d6 instead of a d4. If at least two creatures are within 10 meters of each other, they may roll a d4 as normal.<br><br>You must choose only two creatures to use Enduring Unity.",
    "type":"Class Boon",
  },
  {
    "name":"Undying Burden",
    "cost":3,
    "prereq":"Love Cleric level 9th",
    "desc":"When a creature would drop to 0 hit points as a result of an attack, when you use Shared Burden to reduce that damage, you instead drop to 0 hit points. That creature then heals to its hit point maximum.",
    "type":"Class Boon",
  },
  {
    "name":"Streak of Luck",
    "cost":2,
    "prereq":"Luck Cleric level 3rd",
    "desc":"When you roll a 3 or 4 when you use Fortune's Favor, you may roll an additional 1d4 and add it to the roll's total.",
    "type":"Class Boon",
  },
  {
    "name":"Divine Gambit",
    "cost":3,
    "prereq":"Luck Cleric level 9th",
    "desc":"When any creature within 10 meters of you fails an ability check, skill check, attack, or saving throw, you can use you reaction cause it to succeed. The next ability check, skill check, attack, or saving throw you make fails.<br><br>You may use this feature once, and you gain the ability to do so again when you finish a short or long rest.",
    "type":"Class Boon",
  },
  {
    "name":"Natural Proclivity",
    "cost":2,
    "prereq":"Nature Cleric level 3rd",
    "desc":"The duration a creature is affected by your Charm Animals and Plants becomes 10 minutes, and the effect only ends if they are damaged by one of your allies.",
    "type":"Class Boon",
  },
  {
    "name":"Elemental Cancellation",
    "cost":3,
    "prereq":"Nature Cleric level 9th",
    "desc":"A creature you affect with Dampen Elements becomes immune to the chosen damage type instead of resistant.",
    "type":"Class Boon",
  },
  {
    "name":"Law's Control",
    "cost":2,
    "prereq":"Order Cleric level 3rd",
    "desc":"When you use Order's Demand, you may charm a creature who has immunity to the charmed condition.",
    "type":"Class Boon",
  },
  {
    "name":"Universal Order",
    "cost":3,
    "prereq":"Order Cleric level 9th",
    "desc":"All enchantment spells you cast affect creatures even if they are immune to the charmed condition.",
    "type":"Class Boon",
  },
  {
    "name":"Blessing of Cunning Deceit",
    "cost":2,
    "prereq":"Secrets Cleric level 3rd",
    "desc":"A creature affected by your Blessing of the Whisperer also have advantage on insight checks.",
    "type":"Class Boon",
  },
  {
    "name":"Uncertain Visage",
    "cost":3,
    "prereq":"Secrets Cleric level 9th",
    "desc":"When a creature sees you, they must make a Intelligence saving throw against your spell save DC after they stop looking at you. If they fail, they do not remember any concrete details about any aspect of your appearence. A creature can choose to fail the saving throw, and you can choose for a creature to succeed.",
    "type":"Class Boon",
  },
  {
    "name":"Forceful Wrath",
    "cost":2,
    "prereq":"Tempest Cleric level 3rd",
    "desc":"When a creature fails its saving throw against Wrath of the Storm, it either is pushed away from you a number of meters equal to half of the thunder damage dealt, or pulled toward you a number of meters equal to half of the lightning damage dealt.",
    "type":"Class Boon",
  },
  {
    "name":"Pull of the Cyclone",
    "cost":3,
    "prereq":"Tempest Cleric level 9th",
    "desc":"When you would move a creature further or closer to you by using Forceful Wrath or Tempestuous Strike, you can instead make them go any direction of your choice. Additionally, the minimum distance you move a creature with either one of those abilities becomes 4 meters.",
    "type":"Class Boon",
  },
  {
    "name":"Held Reaction",
    "cost":2,
    "prereq":"Time Cleric level 3rd",
    "desc":"When you hold your action, you do not have to choose a trigger. At any point until the beginning of your next turn, you can choose to trigger your held action.",
    "type":"Class Boon",
  },
  {
    "name":"Planned Action",
    "cost":3,
    "prereq":"Time Cleric level 9th",
    "desc":"You can affect your own and any other one initiative of your choice at the beginning of a round by adding or subtracting 5 to either total.",
    "type":"Class Boon",
  },
  {
    "name":"Vertical Travel",
    "cost":2,
    "prereq":"Travel Cleric level 3rd",
    "desc":"Feather Fall and Levitation become domain spells and count as Cleric spells for you.",
    "type":"Class Boon",
  },
  {
    "name":"Striker's Pilgrimage",
    "cost":3,
    "prereq":"Travel Cleric level 9th",
    "desc":"When a creature moves out of your reach, you may use your reaction to move so that it is still within your reach.",
    "type":"Class Boon",
  },
  {
    "name":"Solid Duplicity",
    "cost":2,
    "prereq":"Trickery Cleric level 3rd",
    "desc":"Your image created from Invoke Duplicity has a solid and realistic form. If a creature touches it, it cannot tell that it is an illusion. You can change your duplicity between solid and illusory as an action on your turn.",
    "type":"Class Boon",
  },
  {
    "name":"Cloak of Trickery",
    "cost":3,
    "prereq":"Trickery Cleric level 9th",
    "desc":"You do not become visible from Cloak of Shadows if you attack or cast a spell.",
    "type":"Class Boon",
  },
  {
    "name":"Courageous Will",
    "cost":2,
    "prereq":"Valor Cleric level 3rd",
    "desc":"All creatures affected by your Aura of Will are also immune to the frightened condition, and gain 1d6 temporary hit points.",
    "type":"Class Boon",
  },
  {
    "name":"Valor Strike",
    "cost":3,
    "prereq":"Valor Cleric level 9th",
    "desc":"If you score a critical hit with a weapon attack against a creature on your turn, one ally that can see you gains a number of temporary hit points equal to the damage you deal with Divine Strike. These temporary hit points disapear at the beginning of your next turn.",
    "type":"Class Boon",
  },
  {
    "name":"Divine Critical",
    "cost":2,
    "prereq":"War Cleric level 3rd",
    "desc":"When you or an ally within 10 meters of you makes a weapon attack, you can use Channel Divinity to make that attack a critical hit. You make this choice after you see the roll, but before the GM says whether the attack hits or misses.",
    "type":"Class Boon",
  },
  {
    "name":"Strikes of War",
    "cost":3,
    "prereq":"War Cleric level 9th",
    "desc":"Your Divine Strike dice become d12's.",
    "type":"Class Boon",
  }];

//Display Subclasses

function domainDisplay(x) {
  document.getElementById("lvl1").innerHTML = divineDomains[x].divineDomain;
  document.getElementById("lvl2").innerHTML = divineDomains[x].divineDomainFeature1;
  document.getElementById("lvl6").innerHTML = divineDomains[x].divineDomainFeature2;
  document.getElementById("lvl8").innerHTML = divineDomains[x].divineDomainFeature3;
  document.getElementById("lvl17").innerHTML = divineDomains[x].divineDomainFeature4;
}
