//Cleric Subclasses

divineDomains = [
  {
    "divineDomain":"<h2>Arcana Domain</h2><hr><p>Magic is an energy that suffuses the multiverse and that fuels both destruction and creation. Gods of the Arcana domain know the secrets and potential of magic intimately. For some of these gods, magical knowledge is a great responsibility that comes with a special understanding of the nature of reality. Other gods of Arcana see magic as pure power, to be used as its wielder sees fit.</p><p>The gods of this domain are often associated with knowledge, as learning and arcane power tend to go hand-in-hand</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Arcana Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Arcane Initiate</h3><p><i>Arcana Domain Cleric Feature</i></p><p>When you choose this domain at 1st level, you gain proficiency in the Arcana skill, and you gain two cantrips of your choice from the wizard spell list. For you, these cantrips count as cleric cantrips.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Arcane Abjuration</h3><p><i>Arcana Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to abjure otherworldly creatures.</p><p>As an action, you present your holy symbol, and one celestial, elemental, fey, or fiend of your choice that is within 10 meters of you must make a Wisdom saving throw, provided that the creature can see or hear you. If the creature fails its saving throw, it is turned for 1 minute or until it takes any damage.</p><p>A turned creature must spend its turns trying to move as far away from you as it can, and it can't willingly end its move in a space within 10 meters of you. It also can't take reactions. For its action, it can use only the Dash action or try to escape from an effect that prevents it from moving. If there's nowhere to move, then the creature can use the Dodge action.</p><p>After you reach 5th level, when a creature fails its saving throw against your Arcane Abjuration feature, the creature is banished for 1 minute (as in the banishment spell, no concentration required) if it isn't on its plane of origin, and its hit dice are at or below a certain threshold, as shown below.</p><table><caption>Arcane Banishment</caption><tr><th>Cleric Level</th><th>Banishes Creatures of Hit Dice...</th></tr><tr><td>5th</td><td>2 or lower</td></tr><tr><td>8th</td><td>3 or lower</td></tr><tr><td>11th</td><td>4 or lower</td></tr><tr><td>5th</td><td>5 or lower</td></tr><tr><td>17th</td><td>6 or lower</td></tr></table>",
    "divineDomainFeature2":"<h3>Spell Breaker</h3><p><i>Arcana Domain Cleric Feature</i></p><p>Starting at 6th level, when you restore hit points to an ally with a spell of 1st level or higher, you can also end one spell of your choice on that creature. The level of the spell you end must be equal to or lower than the level of the spell slot you use to cast the healing spell.</p>",
    "divineDomainFeature3":"<h3>Arcane Mastery</h3><p><i>Arcana Domain Cleric Feature</i></p><p>At 17th level, you choose four spells from the Wizard spell list, one from each of the following levels: 6th, 7th, 8th, and 9th. You add them to your list of domain spells. Like your other domain spells, they are always prepared and count as cleric spells for you.</p>",
  },
  {
    "divineDomain":"<h2>Death Domain</h2><hr><p>The Death domain is concerned with the forces that cause death, as well as the negative energy that gives rise to undead creatures. </p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Death Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Proficiencies</h3><p><i>Death Domain Cleric Feature</i></p><p>When the cleric chooses this domain at 1st level, he or she gains proficiency with the sickle and glaive.</p><h3>Reaper</h3><p><i>Death Domain Cleric Feature</i></p><p>At 1st level, the cleric learns one necromancy cantrip of his or her choice from any spell list. When the cleric casts a necromancy cantrip that normally targets only one creature, the spell can instead target two creatures within range and within 2 meters of each other.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Touch of Death</h3><p><i>Death Domain Cleric Feature</i></p><p>Starting at 2nd level, the cleric can use Channel Divinity to destroy another creature's life force by touch.</p><p>When the cleric hits a creature with a melee attack, the cleric can use Channel Divinity to deal extra necrotic damage to the target. The damage equals 5 + twice his or her cleric level.</p>",
    "divineDomainFeature2":"<h3>Inescapable Destruction</h3><p><i>Death Domain Cleric Feature</i></p><p>Starting at 6th level, the cleric's ability to channel negative energy becomes more potent. Necrotic damage dealt by the character's cleric spells and Channel Divinity options ignores resistance to necrotic damage.</p>",
    "divineDomainFeature3":"<h3>Improved Reaper</h3><p><i>Death Domain Cleric Feature</i></p><p>Starting at 17th level, when the cleric casts a Necromancy spell of 1st through 5th-level that targets only one creature, the spell can instead target two creatures within range and within 2 meters of each other. If the spell consumes its material components, the cleric must provide them for each target.</p>",
  },
  {
    "divineDomain":"<h2>Destruction Domain</h2><hr><p>The Destruction domain is concerned with the forces of undoing, the counterbalance of creation.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Destruction Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Proficiencies</h3><p><i>Destruction Domain Cleric Feature</i></p><p>When you choose this domain at 1st level, you gain proficiency with heavy armor and the maul.</p><h3>Destructive Smite</h3><p><i>Destruction Domain Cleric Feature</i></p><p>Starting from 1st level, when you hit a creature or object with a melee weapon attack, you can expend one spell slot to deal thunder damage to the target, in addition to the weapon's damage. The extra damage is 2d8 for a 1st-level spell slot, plus 1d8 for each spell level higher than 1st, to a maximum of 5d8.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Sundering Invocation</h3><p><i>Destruction Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to channel destructive energy.</p><p>As an action, you touch a creature or a an object within reach. A creature must make a Constitution saving throw, taking 4 x your cleric level thunder damage on a failed saving throw and half as much on a successful one. An object takes 8 x your cleric level thunder damage. If you target an object worn or being held by a creature, they can make a Dexterity saving throw. On a successful save, the object takes no damage.</p>",
    "divineDomainFeature2":"<h3>Appetite for Destruction</h3><p><i>Destruction Domain Cleric Feature</i></p><p>Starting at 6th level, your destructive acts fuel further expressions of devastation. If you kill a creature or destroy an object with a weapon attack, you can use your bonus action to immediately make one additional weapon attack.</p>",
    "divineDomainFeature3":"<h3>Disintigrating Touch</h3><p><i>Destruction Domain Cleric Feature</i></p><p>At 17th level, you can utterly destroy an enemy with just a touch. As an action, touch one creature. That creature must make a Constitution saving throw. The DC for this saving throw is your cleric spell save DC. On a failed save, the creature dies, and its body and everything it is wearing and carrying, except magic items, are reduced to a pile of fine black dust. The creature can be restored to life only by means of a true resurrection or a wish spell. On a successful save, the creature instead takes 10d6 force damage. If this damage reduces the target to 0 hit points, it dies and is disintegrated as if it had failed its save against your Destructive Touch.</p><p>Alternatively, you can use your action to touch one non-magical object that is no larger than 20 meters on a side. That object is then vaporized, and is reduced to a fine white dust. If you touch an object that is larger than 20 meters on a side, you instead vaporize a 20 meter cube of it in the same way.</p><p>Once you use this feature, you can't use it again until you complete a long rest.</p>",
  },
  {
    "divineDomain":"<h2>Forge Domain</h2><hr><p>The gods of the forge are patrons of artisans who work with metal, from a humble blacksmith who keeps a village in horseshoes and plow blades to the mighty elf artisan whose diamond-tipped arrows of mithral have felled demon lords. The gods of the forge teach that, with patience and hard work, even the most intractable metal can be transformed from a lump of ore to a beautifully wrought object. Clerics of these deities search for objects lost to the forces of darkness, liberate mines overrun by orcs, and uncover rare and wondrous materials necessary to create potent magic items. Followers of these gods take great pride in their work, and they are willing to craft and use heavy armor and powerful weapons to protect them.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Forge Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Proficiency</h3><p><i>Forge Domain Cleric Feature</i></p><p>When you choose this domain at 1st level, you gain proficiency with heavy armor and smith's tools.</p><h3>Blessing of the Forge</h3><p><i>Forge Domain Cleric Feature</i></p><p>At 1st level, you gain the ability to imbue magic into a weapon or armor. At the end of a long rest, you can touch one nonmagical object that is a suit of armor or a simple or martial weapon. Until the end of your next long rest or until you die, the object becomes a magic item, granting a +1 bonus to AC if it's armor or a +1 bonus to attack and damage rolls if it's a weapon.</p><p>Once you use this feature, you can't use it again until you finish a long rest.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Artisan's Blessing</h3><p><i>Forge Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to create simple items.</p><p>You conduct an hour-long ritual that crafts a nonmagical item that must include some metal: a simple or martial weapon, a suit of armor, ten pieces of ammunition, a set of tools, or another metal object. The creation is completed at the end of the hour, coalescing in an unoccupied space of your choice on a surface within 2 meters of you.</p><p>The thing you create can be something that is worth no more than 100000 wealth. As part of this ritual, you must lay out metal, which can include coins, with a value equal to the creation. The metal irretrievably coalesces and transforms into the creation at the ritual's end, magically forming even nonmetal parts of the creation. The ritual can create a duplicate of a nonmagical item that contains metal, such as a key, if you possess the original during the ritual.</p>",
    "divineDomainFeature2":"<h3>Soul of the Forge</h3><p><i>Forge Domain Cleric Feature</i></p><p>Starting at 6th level, your mastery of the forge grants you special abilities:</p><ul><li></li>You gain resistance to fire damage.<li>While wearing heavy armor, you gain a +1 bonus to AC.</li></ul></p>",
    "divineDomainFeature3":"<h3>Force of Forge and Flame</h3><p><i>Forge Domain Cleric Feature</i></p><p>At 17th level, your blessed affinity with fire and metal becomes more powerful:<ul><li>You gain immunity to fire damage.</li><li>While wearing heavy armor, you have resistance to bludgeoning, piercing, and slashing damage from nonmagical attacks.</li></ul></p>",
  },
  {
    "divineDomain":"<h2>Grave Domain</h2><hr><p>Gods of the grave watch over the line between life and death. To these deities, death and the afterlife are a foundational part of the multiverse. To desecrate the peace of the dead is an abomination.  Followers of these deities seek to put wandering spirits to rest, destroy the undead, and ease the suffering of the dying. Their magic also allows them to stave off death for a time, particularly for a person who still has some great work to accomplish in the world. This is a delay of death, not a denial of it, for death will eventually get its due.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Grave Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Circle of Mortality</h3><p><i>Grave Domain Cleric Feature</i></p><p>At 1st level, you gain the ability to manipulate the line between life and death. When you would normally roll one or more dice to restore hit points with a spell to a creature at 0 hit points, you instead use the highest number possible for each die.</p><p>In addition, you learn the spare the dying cantrip, which doesn't count against the number of cleric cantrips you know. For you, it has a range of 10 meters, and you can cast it as a bonus action.</p><h3>Eyes of the Grave</h3><p><i>Grave Domain Cleric Feature</i></p><p>At 1st level, you gain the ability to occasionally sense the presence of the undead, whose existence is an insult to the natural cycle of life. As an action, you can open your awareness to magically detect undead. Until the end of your next turn, you know the location of any undead within 20 meters of you that isn't behind total cover and that isn't protected from divination magic. This sense doesn't tell you anything about a creature's capabilities or identity.</p><p>You can use this feature a number of times equal to your Wisdom modifier (minimum of once). You regain all expended uses when you finish a long rest.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Path to the Grave</h3><p><i>Grave Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to mark another creature's life force for termination.</p><p>As an action, you choose one creature you can see within 10 meters of you, cursing it until the end of your next turn. The next time you or an ally of yours hits the cursed creature with an attack, the creature has vulnerability to all of that attack's damage, and then the curse ends.</p>",
    "divineDomainFeature2":"<h3>Sentinel at Death's Door</h3><p><i>Grave Domain Cleric Feature</i></p><p>At 6th level, you gain the ability to impede death's progress. As a reaction when you or a creature you can see within 10 meters of you suffers a critical hit, you can turn that hit into a normal hit. Any effects triggered by a critical hit are canceled.</p><p>You can use this feature a number of times equal to your Wisdom modifier (minimum of once). You regain all expended uses when you finish a long rest.</p>",
    "divineDomainFeature3":"<h3>Keeper of Souls</h3><p><i>Grave Domain Cleric Feature</i></p><p>Starting at 17th level, you can seize a trace of vitality from a parting soul and use it to heal the living. When an enemy you can see dies within 20 meters of you, you or one creature of your choice that is within 20 meters of you regains hit points equal to the enemy's number of Hit Dice. You can use this feature only if you aren't incapacitated. Once you use it, you can't do so again until the start of your next turn.</p>",
  },
  {
    "divineDomain":"<h2>Greed Domain</h2><hr><p>The Greed domain is concerned with personal accumulation of wealth. May it be in the form of coins, magical items, or even fine art, those who follow the domain of Greed seek as much as they can gain. Deities of Greed seek sacrifices of wealth, for they also desire for their own coffers to grow.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Greed Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Proficiencies</h3><p><i>Greed Domain Cleric Feature</i></p><p>When you choose this domain at 1st level, you gain proficiency with heavy armor, and your choice of Deception, Intimidation, Persuasion, or Performance skill checks.</p><h3>Appraiser</h3><p><i>Greed Domain Cleric Feature</i></p><p>Starting at 1st level, you can easily tell the value of objects which you can study. After looking at an object within 2 meters of you for at least 1 minute, you can tell how much wealth it is worth. You also gain the ability to sense whether or not an object is magical if it is within 5 meters of you. In addition, you may cast the identify spell without consuming a spell slot once per long rest. This use of the spell does not require material components.</p><p>The range at which you can sense magical objects increases to 10 meters at 6th level, and to 20 meters at 10th level.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Incite Greed</h3><p><i>Greed Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your action to channel your innate avarice to affect creatures around you. Choose a point within 10 meters of you. All creatures you choose within 10 meters of that point must make a wisdom saving throw. On a failed save, they see an illusory object that they greatly desire appear on that point, and until the end of their next turn they must use their full movement to move toward that point.</p><p>The radius of this ability increases to 20 meters at 10th level.</p>",
    "divineDomainFeature2":"<h3>Divine Frugality</h3><p><i>Greed Domain Cleric Feature</i></p><p>Starting at 6th level, the amount of material components you need for spells is reduced by 25%, and you do not need to provide material components for 1st or 2nd level spells. For example, if a spell calls for 100 grams of diamond dust, you only need to provide 75 grams.</p><p>Additionally, when you cast a spell of 2nd level or higher, you can regain an expended lower level spell slot of 5th level or lower. You can use this ability once, and you regain the ability to do so again when you finish a long rest.</p>",
    "divineDomainFeature3":"<h3>Keeper</h3><p><i>Greed Domain Cleric Feature</i></p><p>Starting at 17th level, your insatiable hunger for collecting is supplemented by divine power.</p><p>You gain 2 additional attunement slots, and you can cast the spells Identify and Locate Object at will.</p><p>Additionally, you gain Demiplane as a domain spell, and it counts as a Cleric spell for you.</p>",
  },
  {
    "divineDomain":"<h2>Knowledge Domain</h2><hr><p>The gods of knowledge value learning and understanding above all. Some teach that knowledge is to be gathered and shared in libraries and universities, or promote the practical knowledge of craft and invention. Some deities hoard knowledge and keep its secrets to themselves. And some promise their followers that they will gain tremendous power if they unlock the secrets of the multiverse. Followers of these gods study esoteric lore, collect old tomes, delve into the secret places of the earth, and learn all they can. Some gods of knowledge promote the practical knowledge of craft and invention.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Knowledge Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Blessings of Knowledge</h3><p><i>Knowledge Domain Cleric Feature</i></p><p>At 1st level, you gain full fluency with two languages of your choice. You also become proficient with your choice of two Knowledge skills.</p><p>Your proficiency bonus is doubled for any ability check you make that uses either of those skills.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Knowledge of the Ages</h3><p><i>Knowledge Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to tap into a divine well of knowledge. As an action, you choose one skill or tool. For 10 minutes, you have proficiency with the chosen skill or tool.</p>",
    "divineDomainFeature2":"<h3>Read Thoughts</h3><p><i>Knowledge Domain Cleric Feature</i></p><p>At 6th level, you can use your Channel Divinity to read a creature's thoughts. You can then use your access to the creature's mind to command it.</p><p>As an action, choose one creature that you can see within 20 meters of you. That creature must make a Wisdom saving throw. If the creature succeeds on the saving throw, you can't use this feature on it again until you finish a long rest.</p><p>If the creature fails its save, you can read its surface thoughts (those foremost in its mind, reflecting its current emotions and what it is actively thinking about) when it is within 20 meters of you. This effect lasts for 1 minute.</p><p>During that time, you can use your action to end this effect and cast the suggestion spell on the creature without expending a spell slot. The target automatically fails its saving throw against the spell.</p><p>Once you use this ability, you cannot do so again until you finish a long rest.</p>",
    "divineDomainFeature3":"<h3>Visions of the Past</h3><p><i>Knowledge Domain Cleric Feature</i></p><p>Starting at 17th level, you can call up visions of the past that relate to an object you hold or your immediate surroundings. You spend at least 1 minute in meditation and prayer, then receive dreamlike, shadowy glimpses of recent events. You can meditate in this way for a number of minutes equal to your Wisdom score and must maintain concentration during that time, as if you were casting a spell.</p><p>Once you use this feature, you can't use it again until you finish a short or long rest.</p><p><strong>Object Reading.</strong> Holding an object as you meditate, you can see visions of the object's previous owner. After meditating for 1 minute, you learn how the owner acquired and lost the object, as well as the most recent significant event involving the object and that owner. If the object was owned by another creature in the recent past (within a number of days equal to your Wisdom score), you can spend 1 additional minute for each owner to learn the same information about that creature.</p><p><strong>Area Reading.</strong> As you meditate, you see visions of recent events in your immediate vicinity (a room, street, tunnel, clearing, or the like, up to a 20-meter cube), going back a number of days equal to your Wisdom score. For each minute you meditate, you learn about one significant event, beginning with the most recent. Significant events typically involve powerful emotions, such as battles and betrayals, marriages and murders, births and funerals. However, they might also include more mundane events that are nevertheless important in your current situation.</p>",
  },
  {
    "divineDomain":"<h2>Life Domain</h2><hr><p>The Life domain focuses on the vibrant positive energy—one of the fundamental forces of the universe—that sustains all life. The gods of life promote vitality and health through healing the sick and wounded, caring for those in need, and driving away the forces of death and undeath.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Life Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Proficiencies</h3><p><i>Life Domain Cleric Feature</i></p><p>When you choose this domain at 1st level, you gain proficiency with heavy armor.</p><h3>Disciple of Life</h3><p><i>Life Domain Cleric Feature</i></p><p>Also starting at 1st level, your healing spells are more effective. Whenever you use a spell of 1st level or higher to restore hit points to a creature, the creature regains additional hit points equal to the spell's level.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Preserve Life</h3><p><i>Life Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to heal the badly injured.</p><p>As an action, you present your holy symbol and evoke healing energy that can restore a number of hit points equal to four times your cleric level. Choose any creatures within 10 meters of you, and divide those hit points among them. This feature can restore a creature to no more than half of its hit point maximum. You can't use this feature on an undead or a construct.</p>",
    "divineDomainFeature2":"<h3>Blessed Healer</h3><p><i>Life Domain Cleric Feature</i></p><p>Beginning at 6th level, the healing spells you cast on others heal you as well. When you cast a spell of 1st level or higher that restores hit points to a creature other than you, you regain hit points equal to the spell's level.</p>",
    "divineDomainFeature3":"<h3>Supreme Healing</h3><p><i>Life Domain Cleric Feature</i></p><p>Starting at 17th level, when you would normally roll one or more dice to restore hit points with a spell, you instead use the highest number possible for each die. For example, instead of restoring 2d6 hit points to a creature, you restore 12.</p>",
  },
  {
    "divineDomain":"<h2>Light Domain</h2><hr><p>Gods of light promote the ideals of rebirth and renewal, truth, vigilance, and beauty, often using the symbol of the sun. Some of these gods are portrayed as the sun itself or as a charioteer who guides the sun across the sky. Others are tireless sentinels whose eyes pierce every shadow and see through every deception. Some are deities of beauty and artistry, who teach that art is a vehicle for the soul's improvement. Clerics of a god of light are enlightened souls infused with radiance and the power of their gods' discerning vision, charged with chasing away lies and burning away darkness.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Light Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Cantrip</h3><p><i>Light Domain Cleric Feature</i></p><p>When you choose this domain at 1st level, you gain the light cantrip if you don't already know it.</p><h3>Warding Flare</h3><p><i>Light Domain Cleric Feature</i></p><p>Also at 1st level, you can interpose divine light between yourself and an attacking enemy. When you are attacked by a creature within 10 meters of you that you can see, you can use your reaction to impose disadvantage on the attack roll, causing light to flare before the attacker before it hits or misses. An attacker that can't be blinded is immune to this feature.</p><p>You can use this feature a number of times equal to your Wisdom modifier (a minimum of once). You regain all expended uses when you finish a long rest.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Radiance of the Dawn</h3><p><i>Light Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to harness sunlight, banishing darkness and dealing radiant damage to your foes.</p><p>As an action, you present your holy symbol, and any magical darkness within 10 meters of you is dispelled. Additionally, each hostile creature within 10 meters of you must make a Constitution saving throw. A creature takes radiant damage equal to 2d8 + your cleric level on a failed saving throw, and half as much damage on a successful one. A creature that has total cover from you is not affected.</p>",
    "divineDomainFeature2":"<h3>Improved Flare</h3><p><i>Light Domain Cleric Feature</i></p><p>Starting at 6th level, you can also use your Warding Flare feature when a creature that you can see within 10 meters of you attacks a creature other than you.</p>",
    "divineDomainFeature3":"<h3>Corona of Light</h3><p><i>Light Domain Cleric Feature</i></p><p>Starting at 17th level, you can use your action to activate an aura of sunlight that lasts for 1 minute or until you dismiss it using another action. You emit bright light in a 20-meter radius and dim light 10 meters beyond that. Your enemies in the bright light have disadvantage on saving throws against any spell that deals fire or radiant damage.</p>",
  },
  {
    "divineDomain":"<h2>Love Domain</h2><hr><p>Love exists in many forms—compassion, infatuation, friendly affection, and passionate love as a few facets. Whatever form these feelings take, the gods of love deepen the bonds between individuals. Clerics of these gods preside over marriages and other familial bonding customs, but they also nurture the emotional bonds of friendship and camaraderie. Their divine blessings bolster and protect allies in battle through these deep bonds and enkindle flares of infatuation to spur their allies and confound their foes.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Love Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Emboldening Bond</h3><p><i>Love Domain Cleric Feature</i></p><p>Starting at 1st level, you can forge an empowering bond between allies. As an action, you can choose two willing creatures you can see within 10 meters of you (this can include yourself) and create a magical bond between them. While either bonded creature is within 10 meters of the other, the creature can roll a d4 and add the number rolled to an attack roll, an ability check, or a saving throw it makes. Each creature can add the d4 no more than once per turn. The bond lasts for 1 hour or until you use this feature again.</p><p>You can use this feature once, and you regain the ability to do so when you finish a long rest.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Shared Burden</h3><p><i>Love Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to share the burden of damage which a creature takes.</p><p>As an reaction when an ally that you can see takes damage, you can use your Channel Divinity to reduce that damage to 0. If you do so, you or a willing ally that you can see takes half the damage that creature was supposed to take.</p>",
    "divineDomainFeature2":"<h3>Protective Bond</h3><p><i>Love Domain Cleric Feature</i></p><p>Beginning at 6th level, the bond you forge between people shields them from harm. While either creature chosen for your Emboldening Bond feature is within 10 meters of the other, the creature can use its reaction to grant resistance to all damage to the other creature when that other creature takes damage. This resistance lasts until the end of the current turn.</p>",
    "divineDomainFeature3":"<h3>Enduring Unity</h3><p><i>Love Domain Cleric Feature</i></p><p>At 17th level, the bonds you create endure across vast distances. Creatures affected by your Emboldening Bond feature gain its benefits, as well as those of your Protective Bond feature, while they are on the same plane of existence as each other.</p><p>Additionally, when a creature chosen for your Emboldening Bond is reduced to 0 hit points, their bonded partner gains the following benefits for 1 minute, or until the creature regains at least 1 hit point:</p><ul><li>The creature has advantage on attack rolls, ability checks, and saving throws.</li><li>The creature gains resistance to all damage.</li><li>As an action, the creature can touch their bonded partner to expend and roll any number of Hit Dice. Their bonded partner regains a number of hit points equal to the total rolled.</li></ul>",
  },
  {
    "divineDomain":"<h2>Luck Domain</h2><hr><p></p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Luck Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Cantrip</h3><p><i>Luck Domain Cleric Feature</i></p><p>When you choose this domain at 1st level, you gain the Guidance cantrip if you do not already have it. This does not count against your number of cantrips known.</p><h3>Fortune's Favor</h3><p><i>Luck Domain Cleric Feature</i></p><p>Beginning at 1st level, you can call upon fortune in order to aid you. As a bonus action on your turn, you may add 1d4 to an ability check, skill check, attack, or saving throw.</p><p>You may use this ability a number of times equal to your Wisdom modifier. You regain all expended uses when you finish a long rest.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Twists of Fate</h3><p><i>Luck Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to alter the outcome of an event.</p><p>As a reaction, you may channel the forces of fate around a creature within 10 meters of you when they make an ability check, skill check, attack, or saving throw. Doing so either adds or subtracts a d6 from that check, your choice.</p>",
    "divineDomainFeature2":"<h3>Siphoned Fortune</h3><p><i>Luck Domain Cleric Feature</i></p><p>Starting at 6th level, your aid in helping others succeed also helps you. When a creature succeeds or fails an ability check, attack roll, or saving throw due to Twists of Fate or a spell you cast that adds or subtracts from their roll, gain advantage on the next ability check, attack roll, or saving throw you make within one minute.</p><p>You may use this ability once. You regain the ability to do so again on a short or long rest.</p>",
    "divineDomainFeature3":"<h3>Luck Favored</h3><p><i>Luck Domain Cleric Feature</i></p><p>You can choose to gain advantage on any ability check, attack roll, or saving throw you make. You must decide to use this feature before you roll.</p><p>You can use this feature a number of times equal to your Wisdom modifier. You regain all expended uses when you finish a long rest.</p>",
  },
  {
    "divineDomain":"<h2>Nature Domain</h2><hr><p>Gods of nature are as varied as the natural world itself, from inscrutable gods of the deep forests to friendly deities associated with particular springs and groves. Druids revere nature as a whole and might serve one of these deities, practicing mysterious rites and reciting all-but-forgotten prayers in their own secret tongue. But many of these gods have clerics as well, champions who take a more active role in advancing the interests of a particular nature god. These clerics might hunt the evil monstrosities that despoil the woodlands, bless the harvest of the faithful, or wither the crops of those who anger their gods.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Nature Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Acolyte of Nature</h3><p><i>Nature Domain Cleric Feature</i></p><p>At 1st level, you learn one druid cantrip of your choice. You also gain proficiency with two of the following skills of your choice: Animal Handling, Nature, Prima, or Survival.</p><h3>Bonus Proficiency</h3><p><i>Nature Domain Cleric Feature</i></p><p>Also at 1st level, you gain proficiency with heavy armor and the Quarterstaff.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Charm Animals and Plants</h3><p><i>Nature Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to charm animals and plants.</p><p>As an action, you present your holy symbol and invoke the name of your deity. Each beast or plant creature that can see you within 10 meters of you must make a Wisdom saving throw. If the creature fails its saving throw, it is charmed by you for 1 minute or until it takes damage. While it is charmed by you, it is friendly to you and other creatures you designate.</p>",
    "divineDomainFeature2":"<h3>Dampen Elements</h3><p><i>Nature Domain Cleric Feature</i></p><p>Starting at 6th level, when you or a creature within 10 meters of you takes acid, cold, fire, lightning, or thunder damage, you can use your reaction to grant resistance to the creature against that instance of the damage.</p>",
    "divineDomainFeature3":"<h3>Master of Nature</h3><p><i>Nature Domain Cleric Feature</i></p><p>At 17th level, you gain the ability to command animals and plant creatures. While creatures are charmed by your Charm Animals and Plants feature, you can take a bonus action on your turn to verbally command what each of those creatures will do on its next turn.</p>",
  },
  {
    "divineDomain":"<h2>Order Domain</h2><hr><p>The Order Domain represents discipline, as well as devotion to a society or an institution and strict obedience to the laws governing it. </p><p>The ideal of order is obedience to the law above all else, rather than to a specific individual or the passing influence of emotion or popular rule. Clerics of order are typically concerned with how things are done, rather than whether an action's results are just. Following the law and obeying its edicts is critical, especially when it benefits these clerics and their guilds or deities.</p><p>Law establishes hierarchies. Those selected by the law to lead must be obeyed. Those who obey must do so to the best of their ability. In this manner, law creates an intricate web of obligations that allows society to forge order and security in a chaotic multiverse.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Order Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Proficiencies</h3><p><i>Order Domain Cleric Feature</i></p><p>When you choose this domain at 1st level, you gain proficiency with heavy armor. You also gain proficiency in the Intimidation or Persuasion skill (your choice).</p><h3>Voice of Authority</h3><p><i>Order Domain Cleric Feature</i></p><p>Starting at 1st level, you can invoke the power of law to drive an ally to attack. If you cast a spell with a spell slot of 1st level or higher and target an ally with the spell, that ally can use their reaction immediately after the spell to make one weapon attack against a creature of your choice that you can see.</p><p>If the spell targets more than one ally, you choose the ally who can make the attack.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Order's Demand</h3><p><i>Order Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to exert an intimidating presence over others.</p><p>As an action, you present your holy symbol, and each creature of your choice that can see or hear you within 10 meters of you must succeed on a Wisdom saving throw or be charmed by you until the end of your next turn or until the charmed creature takes any damage. You can also cause any of the charmed creatures to drop what they are holding when they fail the saving throw.</p>",
    "divineDomainFeature2":"<h3>Embodiment of the Law</h3><p><i>Order Domain Cleric Feature</i></p><p>At 6th level, you become remarkably adept at channeling magical energy to compel others.</p><p>If you cast a spell of the enchantment school using a spell slot of 1st level or higher, you can change the spell's casting time to 1 bonus action for this casting, provided the spell's casting time is normally 1 action.</p><p>You can use this feature a number of times equal to your Wisdom modifier (minimum of once), and you regain all expended uses of it when you finish a long rest.</p>",
    "divineDomainFeature3":"<h3>Order's Wrath</h3><p><i>Order Domain Cleric Feature</i></p><p>Starting at 17th level, enemies you designate for destruction wilt under the combined efforts of you and your allies. If you deal your Divine Strike damage to a creature on your turn, you can curse that creature until the start of your next turn. The next time one of your allies hits the cursed creature with an attack, the target also takes 2d8 psychic damage, and the curse ends. You can curse a creature in this way only once per turn.</p>",
  },
  {
    "divineDomain":"<h2>Shadow Domain</h2><hr><p>The Shadow domain concerns itself with the forces of darkness, and the immaterial. Hiding away the things in this world that should not be known, clerics of Shadow are forces whose movements are made unseen. Deities of Shadow act as the natural counterbalance of Light, and hold back blazing radiance from consuming the universe. Due to this nature, the forces of Shadow also naturally associate with the cold.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Shadow Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Proficiencies</h3><p><i>Shadow Domain Cleric Feature</i></p><p>You gain proficiency with the Deception and Stealth skills.</p><h3>Eyes of the Dark</h3><p><i>Shadow Domain Cleric Feature</i></p><p>You can see in magical and non magical darkness as if it were dim light out to a range of 10 meters, and dim light as if it were bright light out to the same range.</p><p>This range increases to 20 meters at 6th level, and 30 meters at 10th level.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Obscure in Shade</h3><p><i>Shadow Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to harness the power of shadow. As an action, choose yourself or a creatures within 10 meters of you. For the next minute, they gain the following benefits:</p><ul><li>A +1 bonus to AC.</li><li>A +5 bonus to stealth checks.</li><li>Attack rolls made against them while they are in dim light or darkness are made at disadvantage.</li></ul>",
    "divineDomainFeature2":"<h3>Aura of Darkness</h3><p><i>Shadow Domain Cleric Feature</i></p><p>At 6th level, you gain an aura of darkness that you can activate and dismiss as an action. While this aura is activated, non magical light and darkness is affected in the following ways:</p><ul><li>Bright light out to a radius of 30 meters around you becomes dim light.</li><li>Dim light out to a radius of 20 meters around you becomes darkness.</li><li>Darkness out to a radius of 10 meters around you becomes magical darkness.</li></ul>",
    "divineDomainFeature3":"<h3>Revenant of Shadow</h3><p><i>Shadow Domain Cleric Feature</i></p><p>At 17th level, your power over darkness turns your form into a force of shadow. Additionally, you gain the following benefits:</p><ul><li>You can use your bonus action to surround a creature within 20 meters of you in shade. They become blinded until the beginning of your next turn.</li><li>Creatures you choose when you activate Aura of Darkness can see through its magical and non magical darkness as if it were dim light, and its dim light as if it were bright light.</li><li>You can see in magical and non magical darkness and dim light as if it were bright light out to any range.</li></ul>",
  },
  {
    "divineDomain":"<h2>Tempest Domain</h2><hr><p>Gods whose portfolios include the Tempest domain govern storms, sea, and, sky. They include gods of lightning and thunder, gods of earthquakes, some fire gods, and certain gods of violence, physical strength, and courage. In some pantheons, a god of this domain rules over other deities and is known for swift justice delivered by thunderbolts. In the pantheons of seafaring people, gods of this domain are ocean deities and the patrons of sailors. Tempest gods send their clerics to inspire fear in the common folk, either to keep those folk on the path of righteousness or to encourage them to offer sacrifices of propitiation to ward off divine wrath.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Tempest Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Proficiencies</h3><p><i>Tempest Domain Cleric Feature</i></p><p>At 1st level, you gain proficiency with all ranged weapons.</p><h3>Wrath of the Storm</h3><p><i>Tempest Domain Cleric Feature</i></p><p>Also at 1st level, you can thunderously rebuke attackers. When a creature within 10 meters of you that you can see hits you with an attack, you can use your reaction to cause the creature to make a Dexterity saving throw. The creature takes 2d6 lightning or thunder damage (your choice) on a failed saving throw, and half as much damage on a successful one.</p><p>You can use this feature a number of times equal to your Wisdom modifier (a minimum of once). You regain all expended uses when you finish a long rest.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Destrictive Wrath</h3><p><i>Tempest Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to wield the power of the storm with unchecked ferocity.</p><p>When you roll lightning or thunder damage, you can use your Channel Divinity to deal maximum damage, instead of rolling.</p>",
    "divineDomainFeature2":"<h3>Tempestuous Strike</h3><p><i>Tempest Domain Cleric Feature</i></p><p>At 6th level, when you deal thunder or lightning damage to a Large or smaller creature, you can also push it up to 3 meters away from you if you deal thunder damage, or pull it up to 3 meters closer to you if you deal lightning damage.</p>",
    "divineDomainFeature3":"<h3>Stormborn</h3><p><i>Tempest Domain Cleric Feature</i></p><p>At 17th level, you have a flying speed equal to your current walking speed whenever you are not underground or indoors.</p>",
  },
  {
    "divineDomain":"<h2>Time Domain</h2><hr><p>The Time domain concerns itself with preserving the natural order of time, and its sacred motion of constantly moving forward. However, those chosen with this preservation also gain the ability to manipulate this motion to a certain degree. Deities of time are tasked with keeping certain that events in the past stay in the past, and events that have yet to come are never to be fully known. Therefore, deities who preside over fate also maintain the domain of Time.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Time Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Prescience</h3><p><i>Time Domain Cleric Feature</i></p><p>At 1st level, you are immune to being surprised and may act during surprise rounds.</p><h3>Bodily Stasis</h3><p><i>Time Domain Cleric Feature</i></p><p>Starting at 1st level, your body is less affected by the flow of time. For every number of years equal to your proficiency bonus that pass, you age only 1 year.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Time Echo</h3><p><i>Time Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to create a duplicate of yourself from a possible future that is now impossible to be.</p><p>As an action, you may choose a point within 20 meters of you. On the spot that you choose, a translucent visage of yourself appears and lasts until the beginning of your next turn. This echo has your game statistics, but cannot cast spells of 5th level or higher or use Channel Divinity. It acts on its own initiative, although you may control this visage (as it acts as you would). Any spell slots your echo uses or damage it takes does not transfer to you. When this visage dissipates, you may use your reaction to teleport into its space.</p><p>At 10th level, you create two echoes, instead of one, when you use this ability. You roll initiative separately for each.</p>",
    "divineDomainFeature2":"<h3>Chronomancer</h3><p><i>Time Domain Cleric Feature</i></p><p>At 6th level, you better gain influence over the fluxes of time. You gain a bonus to your initiative rolls equal to your Wisdom modifier.</p><p>In addition, you can cast spells that have a casting time of 1 minute or longer in half the time, rounded down.</p>",
    "divineDomainFeature3":"<h3>Master of Time</h3><p><i>Time Domain Cleric Feature</i></p><p>At 17th level, your mastery over time allows you to become immune to magical and non-magical aging. You may activate and disable this ability when you finish a long rest.</p><p>Additionally, Time Stop and Foresight become domain spells for you, and counts as cleric spells for you. </p>",
  },
  {
    "divineDomain":"<h2>Travel Domain</h2><hr><p>The Travek domain concerns itself with change in location. Anywhere from a wayward vagabond wandering the countryside, a sailor traversing the open seas, to a soul drifting its way through the planes. Clerics of Travel are expected to help any travellers they meet, and ensure routes that become blocked are freed once again. Deities of Travel protect these journeys, and ensures that the travel between planes and teleportation maintains possibility.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Travel Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Fleet of Foot</h3><p><i>Travel Domain Cleric Feature</i></p><p>When you choose this domain at 1st level, your walking speed increases by a number of meters equal to your Wisdom modifier.</p><p>Additionally, you do not provoke attacks of opportunity by leaving a creature's reach.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Swift Pace</h3><p><i>Travel Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to make you and your allies quicker in speed.</p><p>As an action, any creatures you choose (including you) within 10 meters gain the following benefits for 1 minute:</p><ul><li>Walking speed increases by a number of meters equal to two times your Wisdom modifier.</li><li>Can use the dash action as a bonus action.</li></ul>",
    "divineDomainFeature2":"<h3>Endurance of the Traveller</h3><p><i>Travel Domain Cleric Feature</i></p><p>Beginning at 6th level, you do not receive exhaustion by traveling. As an action, you may transfer this endurance to a creature within 10 meters of you. While transferred in this way, you do not gain the benefits of this feature, but the creature you choose does. This transference lasts until you dismiss it as an action, or until the creature moves farther than 10 meters away from you for more than 1 minute.</p><p>Additionally, you may travel at a swift pace and not receive disadvantage on stealth or perception checks.</p>",
    "divineDomainFeature3":"<h3>Divine Traveler</h3><p><i>Travel Domain Cleric Feature</i></p><p>At 17th level, you always have the spell teleport prepared and it counts as a Cleric spell for you. As long as you have been to a location once, you can travel to that location at a 100% success rate.</p><p>Additionally, your walking speed increases by an additional 10 meters.</p>",
  },
  {
    "divineDomain":"<h2>Trickery Domain</h2><hr><p>Gods of trickery are mischief-makers and instigators who stand as a constant challenge to the accepted order among both gods and mortals. They're patrons of thieves, scoundrels, gamblers, rebels, and liberators. Their clerics are a disruptive force in the world, puncturing pride, mocking tyrants, stealing from the rich, freeing captives, and flouting hollow traditions. They prefer subterfuge, pranks, deception, and theft rather than direct confrontation.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Trickery Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Blessing of the Trickster</h3><p><i>Trickery Domain Cleric Feature</i></p><p>Starting when you choose this domain at 1st level, you can use your action to touch a willing creature other than yourself to give it advantage on Dexterity (Stealth) checks. This blessing lasts for 1 hour or until you use this feature again.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Invoke Duplicity</h3><p><i>Trickery Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to create an illusory duplicate of yourself.</p><p>As an action, you create a perfect illusion of yourself that lasts for 1 minute, or until you lose your concentration (as if you were concentrating on a spell). The illusion appears in an unoccupied space that you can see within 10 meters of you. As a bonus action on your turn, you can move the illusion up to 10 meters to a space you can see, but it must remain within 40 meters of you.</p><p>For the duration, you can cast spells as though you were in the illusion's space, but you must use your own senses. Additionally, when both you and your illusion are within 1 meter of a creature that can see the illusion, you have advantage on attack rolls against that creature, given how distracting the illusion is to the target.</p>",
    "divineDomainFeature2":"<h3>Cloak of Shadows</h3><p><i>Trickery Domain Cleric Feature</i></p><p>Starting at 6th level, you can use your Channel Divinity to vanish.</p><p>As an action, you become invisible for 1d4 turns. You become visible if you attack or cast a spell.</p>",
    "divineDomainFeature3":"<h3>Improved Duplicity</h3><p><i>Trickery Domain Cleric Feature</i></p><p>At 17th level, you can create up to four duplicates of yourself, instead of one, when you use Invoke Duplicity. As a bonus action on your turn, you can move any number of them up to 10 meters, to a maximum range of 40 meters away from you.</p>",
  },
  {
    "divineDomain":"<h2>Valor Domain</h2><hr><p></p>The Valor domain concerns itself with hope and courage, both on and off of the battlefield. Cowardice, as those who preach Valor attest, is a disgraceful and selfish action that should be avoided at all costs, and giving up should never be something one should do. Deities of Valor invoke power in great heroes that embody their ideals, and are the first lines of defense on the divine battlefield.<p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>Valor Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Bonus Proficiencies</h3><p><i>Valor Domain Cleric Feature</i></p>When you choose this domain at 1st level, you gain proficiency with heavy armor and all melee martial weapons.<p></p><h3>Courageous Initiation</h3><p><i>Valor Domain Cleric Feature</i></p><p>Starting at 1st level, you add your Wisdom modifier to initiative checks.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: Last Stand</h3><p><i>Valor Domain Cleric Feature</i></p><p>Starting at 2nd level, you can use your Channel Divinity to let courage be shown near one's last moments on the battlefield.</p><p>As a reaction when a creature you see or yourself is reduced to 0 hit points, you can invoke the power of courage to instead bring them to 1 hit point.</p>",
    "divineDomainFeature2":"<h3>Rush to Glory</h3><p><i>Valor Domain Cleric Feature</i></p><p>Beginning at 6th level, you may use your bonus action to dash as long as you are moving toward an ally or enemy that you can see.</p>",
    "divineDomainFeature3":"<h3>Heart of Valor</h3><p><i>Valor Domain Cleric Feature</i></p><p>Starting at 17th level, you become the embodiment of courage. You become immune to the frightened condition, and the first death saving throw you make after you finish a long rest is a natural 20.</p><p>Additionally, if you are reduced to 0 hit points, all allies within 10 meters of you gain a number of temporary hit points equal to half your Cleric level. Once you use this ability, you cannot do so again until you finish a long rest.</p>",
  },
  {
    "divineDomain":"<h2>War Domain</h2><hr><p>War has many manifestations. It can make heroes of ordinary people. It can be desperate and horrific, with acts of cruelty and cowardice eclipsing instances of excellence and courage. In either case, the gods of war watch over warriors and reward them for their great deeds. The clerics of such gods excel in battle, inspiring others to fight the good fight or offering acts of violence as prayers. Gods of war include champions of honor and chivalry as well as gods of destruction and pillage and gods of conquest and domination. Other war gods take a more neutral stance, promoting war in all its manifestations and supporting warriors in any circumstance.</p><p>At each indicated cleric level, add the listed spells to your spells prepared. They do not count towards your limit.</p><table><caption>War Domain Spells</caption><tr><th>Cleric Level</th><th>Spells</th></tr><tr><td>1st</td><td></td></tr><tr><td>3rd</td><td></td></tr><tr><td>5th</td><td></td></tr><tr><td>7th</td><td></td></tr><tr><td>9th</td><td></td></tr></table><h3>Blood of the Battlefield</h3><p><i>War Domain Cleric Feature</i></p><p>At 1st level, you gain proficiency with all weapons and armor.</p><h3>War Priest</h3><p><i>War Domain Cleric Feature</i></p><p>From 1st level, your god delivers bolts of inspiration to you while you are engaged in battle. When you use the Attack action, you can make one weapon attack as a bonus action.</p><p>You can use this feature a number of times equal to your Wisdom modifier (a minimum of once). You regain all expended uses when you finish a long rest.</p>",
    "divineDomainFeature1":"<h3>Channel Divinity: War God's Blessing</h3><p><i>War Domain Cleric Feature</i></p><p>At 2nd level, when you or a creature within 10 meters of you makes an attack roll, you can use your reaction to grant that creature a +10 bonus to the roll, using your Channel Divinity. You make this choice after you see the roll, but before the GM says whether the attack hits or misses.</p>",
    "divineDomainFeature2":"<h3>Resilience of the War God</h3><p><i>War Domain Cleric Feature</i></p><p>Beginning at 6th level, your health is supplemented by the power of your deity. When you are healed for hit points, you also gain a number of temporary hit points equal to half of the hit points healed. These temporary hit points disappear at the end of your next turn.</p>",
    "divineDomainFeature3":"<h3>Avatar of Battle</h3><p><i>War Domain Cleric Feature</i></p><p>At 17th level, you gain a +2 bonus to AC. Additionally, you gain a number of temporary hit points at the beginning of your turn equal to your Wisdom modifier + 1.</p>",
  },


];

//Cleric Class Boons

var classBoon = [
  {
    "name":"Deepened Divinity",
    "cost":3,
    "prereq":"Cleric or Paladin level 3rd",
    "desc":"You gain one additional use of Channel Divinity per long rest.",
    "type":"Class Boon",
  },
  {
    "name":"Improved Divine Intervention",
    "cost":3,
    "prereq":"Cleric level 10th",
    "desc":"When you use Divine Intervention, you gain a 10% greater chance of intervention.",
    "type":"Class Boon",
  },
  {
    "name":"Encompassing Abjure",
    "cost":2,
    "prereq":"Arcana Cleric level 3rd",
    "desc":"You can target up to two additional celestials, elementals, fey, or fiends when you use Arcane Abjuration.",
    "type":"Class Boon",
  },
  {
    "name":"Weave Sapper",
    "cost":3,
    "prereq":"Arcana Cleric level 9th",
    "desc":"When you end a spell that you did not cast on a creature or object, you gain a number of temporary hit points equal to 1d6 * the level of the spell.",
    "type":"Class Boon",
  },
  {
    "name":"Reaping Touch",
    "cost":2,
    "prereq":"Death Cleric level 3rd",
    "desc":"When you deal damage to a creature with Touch of Death, you also gain a number of hit points equal to half the damage dealt. If this would bring your current hit points past your hit point maximum, any left over hit points become temporary hit points.",
    "type":"Class Boon",
  },
  {
    "name":"Necrotic Mastery",
    "cost":3,
    "prereq":"Death Cleric level 9th",
    "desc":"Necrotic damage dealt by your cleric spells and Channel Divinity options ignores resistance and immunity to necrotic damage. Additionally, you gain resistance to necrotic damage.",
    "type":"Class Boon",
  },
  {
    "name":"Sundering Strike",
    "cost":2,
    "prereq":"Destruction Cleric level 3rd",
    "desc":"When you score a critical hit with a weapon attack, you can choose to use Sundering Invocation. When you use it in this way, a creature has disadvantage on the saving throw.",
    "type":"Class Boon",
  },
  {
    "name":"Inured to Annihilation",
    "cost":3,
    "prereq":"Destruction Cleric level 9th",
    "desc":"You gain immunity to thunder damage.",
    "type":"Class Boon",
  },
  {
    "name":"Greater Blessing of the Forge",
    "cost":2,
    "prereq":"Forge Cleric level 3rd",
    "desc":"When you use Blessing of the Forge, the bonus to a weapon or armor becomes +2.",
    "type":"Class Boon",
  },
  {
    "name":"Hammer of Creation",
    "cost":3,
    "prereq":"Forge Cleric level 9th",
    "desc":"You can use your Channel Divinity to conduct an hour-long ritual on a magical weapon. At the end of this ritual, this weapon gains the following properties:<ul><li>This weapon ignores all resistance to Fire damage.</li><li>This weapon deals an additional 1d6 Fire damage.</li></ul>These properties last for 8 hours, or until you use your Channel Divinity again.",
    "type":"Class Boon",
  },
  {
    "name":"Grave Usher",
    "cost":2,
    "prereq":"Grave Cleric level 3rd",
    "desc":"When you reduce a creature to 0 hit points, you can choose to expend a spell slot of 1st level or higher to instantly kill them. When you kill a creature in this way, their body cannot become undead for a number of days equal to the spell slot level you expended.",
    "type":"Class Boon",
  },
  {
    "name":"Cemetary Gates",
    "cost":3,
    "prereq":"Forge Cleric level 9th",
    "desc":"When a creature within 10 meters of you dies, you can use your Channel Divinity as a reaction to bring the creature to 1 hit point instead. They also lose one level of exhaustion.",
    "type":"Class Boon",
  },
  {
    "name":"Incite Envy",
    "cost":2,
    "prereq":"Greed Cleric level 3rd",
    "desc":"When you use Incite Greed, you can choose to target a creature within range instead of a point. All creatures within the affected area that fail the saving throw must also make an additional wisdom saving throw if they get within range of the creature you choose. On a fail, they must use their action to attack that creature.",
    "type":"Class Boon",
  },
  {
    "name":"Divine Frugality",
    "cost":3,
    "prereq":"Greed Cleric level 9th",
    "desc":"The cost of material components you need for spells becomes 40% cheaper. Additionally, you do not need to provide the material components for spells that are less than 10000 wealth.",
    "type":"Class Boon",
  },
  {
    "name":"Expertise of the Ages",
    "cost":2,
    "prereq":"Knowledge Cleric level 3rd",
    "desc":"When you gain proficiency in a skill using Knowledge of the Ages, you double your proficiency bonus for that skill.",
    "type":"Class Boon",
  },
  {
    "name":"Intrusive Introspection",
    "cost":3,
    "prereq":"Knowledge Cleric level 9th",
    "desc":"You can expend a spell slot instead of your Channel Divinity to use Read Thoughts.",
    "type":"Class Boon",
  },
  {
    "name":"Cling to Life",
    "cost":2,
    "prereq":"Life Cleric level 3rd",
    "desc":"When you or a creature within 10 meters of you falls to 0 hit points, you can use your reaction to expend a spell slot. They gain a number of hit points equal to two * the level of spell slot expended. You cannot heal an undead or construct in this way.",
    "type":"Class Boon",
  },
  {
    "name":"Stolen Recovery",
    "cost":3,
    "prereq":"Life Cleric level 9th",
    "desc":"When a creature within 10 meters of you gains hit points, you can use your reaction and expend a use of your Channel Divinity to reduce all healing that creature received to 0. A creature within 10 meters of you then heals for a number of hit points equal to half of the hit points the initial target was intended to gain. You cannot heal an undead or construct in this way.",
    "type":"Class Boon",
  },
  {
    "name":"Radiant Flare",
    "cost":2,
    "prereq":"Light Cleric level 3rd",
    "desc":"When a creature is affected by your Warding Flare, they automatically miss their attack and take 1d10 + half your cleric level radiant damage.",
    "type":"Class Boon",
  },
  {
    "name":"Blinding Dawn",
    "cost":3,
    "prereq":"Light Cleric level 9th",
    "desc":"When you use Radiance of the Dawn, all creatures that fail the Constitution saving throw are also blinded for 1 minute.",
    "type":"Class Boon",
  },
  {
    "name":"Family Bond",
    "cost":2,
    "prereq":"Love Cleric level 3rd",
    "desc":"When you use Emboldening Bond, you may instead choose a number of creatures up to your Wisdom modifier. If all creatures are within 10 meters of each other, they may roll a d6 instead of a d4. If at least two creatures are within 10 meters of each other, they may roll a d4 as normal.<br><br>You must choose only two creatures to use Enduring Unity.",
    "type":"Class Boon",
  },
  {
    "name":"Undying Burden",
    "cost":3,
    "prereq":"Love Cleric level 9th",
    "desc":"When a creature would drop to 0 hit points as a result of an attack, when you use Shared Burden to reduce that damage, you instead drop to 0 hit points. That creature then heals to its hit point maximum.",
    "type":"Class Boon",
  },
  {
    "name":"Streak of Luck",
    "cost":2,
    "prereq":"Luck Cleric level 3rd",
    "desc":"When you roll a 3 or 4 when you use Fortune's Favor, you may roll an additional 1d4 and add it to the roll's total.",
    "type":"Class Boon",
  },
  {
    "name":"Divine Gambit",
    "cost":3,
    "prereq":"Luck Cleric level 9th",
    "desc":"When any creature within 10 meters of you fails an ability check, skill check, attack, or saving throw, you can use you reaction cause it to succeed. The next ability check, skill check, attack, or saving throw you make fails.<br><br>You may use this feature once, and you gain the ability to do so again when you finish a short or long rest.",
    "type":"Class Boon",
  },
  {
    "name":"Natural Proclivity",
    "cost":2,
    "prereq":"Nature Cleric level 3rd",
    "desc":"The duration a creature is affected by your Charm Animals and Plants becomes 10 minutes, and the effect only ends if they are damaged by one of your allies.",
    "type":"Class Boon",
  },
  {
    "name":"Elemental Cancellation",
    "cost":3,
    "prereq":"Nature Cleric level 9th",
    "desc":"A creature you affect with Dampen Elements becomes immune to the chosen damage type instead of resistant.",
    "type":"Class Boon",
  },
  {
    "name":"Law's Control",
    "cost":2,
    "prereq":"Order Cleric level 3rd",
    "desc":"When you use Order's Demand, you may charm a creature who has immunity to the charmed condition.",
    "type":"Class Boon",
  },
  {
    "name":"Universal Order",
    "cost":3,
    "prereq":"Order Cleric level 9th",
    "desc":"All enchantment spells you cast affect creatures even if they are immune to the charmed condition.",
    "type":"Class Boon",
  },
  {
    "name":"Obscure in Black",
    "cost":2,
    "prereq":"Shadow Cleric level 3rd",
    "desc":"A creature affected by your Obscure in Shade gain an additional +1 bonus to AC and immunity to the blinded condition.",
    "type":"Class Boon",
  },
  {
    "name":"Aura of Deep Darkness",
    "cost":3,
    "prereq":"Shadow Cleric level 9th",
    "desc":"Your Aura of Darkness can affect magical bright light, and is changed in the following ways:<ul><li>Bright light out to a radius of 30 meters around you becomes darkness.</li><li>Dim light out to a radius of 20 meters around you becomes magical darkness.</li></ul>",
    "type":"Class Boon",
  },
  {
    "name":"Forceful Wrath",
    "cost":2,
    "prereq":"Tempest Cleric level 3rd",
    "desc":"When a creature fails its saving throw against Wrath of the Storm, it either is pushed away from you a number of meters equal to half of the thunder damage dealt, or pulled toward you a number of meters equal to half of the lightning damage dealt.",
    "type":"Class Boon",
  },
  {
    "name":"Pull of the Cyclone",
    "cost":3,
    "prereq":"Tempest Cleric level 9th",
    "desc":"When you would move a creature further or closer to you by using Forceful Wrath or Tempestuous Strike, you can instead make them go any direction of your choice. Additionally, the minimum distance you move a creature with either one of those abilities becomes 4 meters.",
    "type":"Class Boon",
  },
  {
    "name":"Held Reaction",
    "cost":2,
    "prereq":"Time Cleric level 3rd",
    "desc":"When you hold your action, you do not have to choose a trigger. At any point until the beginning of your next turn, you can choose to trigger your held action.",
    "type":"Class Boon",
  },
  {
    "name":"Planned Action",
    "cost":3,
    "prereq":"Time Cleric level 9th",
    "desc":"You can affect your own and any other one initiative of your choice at the beginning of a round by adding or subtracting 5 to either total.",
    "type":"Class Boon",
  },
  {
    "name":"Vertical Travel",
    "cost":2,
    "prereq":"Travel Cleric level 3rd",
    "desc":"Feather Fall and Levitation become domain spells and count as Cleric spells for you.",
    "type":"Class Boon",
  },
  {
    "name":"Striker's Pilgrimage",
    "cost":3,
    "prereq":"Travel Cleric level 9th",
    "desc":"When a creature moves out of your reach, you can use your reaction to move within reach of that creature before the start of your next turn.",
    "type":"Class Boon",
  },
  {
    "name":"Solid Duplicity",
    "cost":2,
    "prereq":"Trickery Cleric level 3rd",
    "desc":"Your image created from Invoke Duplicity has a solid and realistic form. If a creature touches it, it cannot tell that it is an illusion. You can change your duplicity between solid and illusory as an action on your turn.",
    "type":"Class Boon",
  },
  {
    "name":"Cloak of Trickery",
    "cost":3,
    "prereq":"Trickery Cleric level 9th",
    "desc":"You do not become visible from Cloak of Shadows if you attack or cast a spell.",
    "type":"Class Boon",
  },
  {
    "name":"Courageous Will",
    "cost":2,
    "prereq":"Valor Cleric level 3rd",
    "desc":"All creatures affected by your Aura of Will are also immune to the frightened condition, and gain 1d6 temporary hit points.",
    "type":"Class Boon",
  },
  {
    "name":"Valor Strike",
    "cost":3,
    "prereq":"Valor Cleric level 9th",
    "desc":"If you score a critical hit with a weapon attack against a creature on your turn, one ally that can see you gains a number of temporary hit points equal to the damage you deal with Divine Strike. These temporary hit points disapear at the beginning of your next turn.",
    "type":"Class Boon",
  },
  {
    "name":"Divine Critical",
    "cost":2,
    "prereq":"War Cleric level 3rd",
    "desc":"When you or an ally within 10 meters of you makes a weapon attack, you can use Channel Divinity to make that attack a critical hit. You make this choice after you see the roll, but before the GM says whether the attack hits or misses.",
    "type":"Class Boon",
  },
  {
    "name":"Drums of War",
    "cost":3,
    "prereq":"War Cleric level 9th",
    "desc":"When you take the attack action on your turn, you can use your bonus action to make a single weapon attack.",
    "type":"Class Boon",
  }];

//Display Subclasses

function domainDisplay(x) {
  document.getElementById("lvl1").innerHTML = c1[2].lvl1;
  document.getElementById("lvl2").innerHTML = c1[2].lvl2;
  document.getElementById("lvl6").innerHTML = c1[2].lvl6;
  document.getElementById("lvl17").innerHTML = c1[2].lvl17;
  document.getElementById("lvl1").innerHTML += divineDomains[x].divineDomain;
  document.getElementById("lvl2").innerHTML += divineDomains[x].divineDomainFeature1;
  document.getElementById("lvl6").innerHTML += divineDomains[x].divineDomainFeature2;
  document.getElementById("lvl17").innerHTML += divineDomains[x].divineDomainFeature3;
}
